### ISSUE TITLE
Tests fail on python 3.5

### ISSUE THREAD

**Issue by itziakos** [enthought/envisage#85] opened 2017-01-18 17:35 UTC
When running the envisage tests under python 3.5 we have a good amount of failures.

(see https://travis-ci.org/enthought/envisage/jobs/193117479)

**Comment by dpinte** [comment] 2017-01-18 19:07
@itziakos the issue is missing eggs in here https://github.com/enthought/envisage/tree/master/envisage/tests/bad_eggs and  https://github.com/enthought/envisage/tree/master/envisage/tests/eggs

**Comment by dpinte** [comment] 2017-01-18 19:14
@itziakos IIRC I have a branch on my laptop that fixes all that. I can push that later today.

**Comment by itziakos** [comment] 2017-01-18 21:00
Thanks @dpinte, the test output is really messy and does not help. The tests should skip with a proper message when the eggs are missing.

**Comment by dpinte** [comment] 2017-01-18 21:04
@itziakos I agree. That code was messy and I definitely lost two hours last week just trying to understand why it was not working. I'll see what I did in the code when fixing the problem

**Comment by dpinte** [comment] 2017-01-19 09:06
Fixed by #86

**Closed by dpinte** 2017-01-19 09:06 UTC
Labels: Bug
