### ISSUE TITLE
ZMQ deprecation warning in test suite

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#224] opened 2019-09-21 09:45 UTC
`
test_initial_namespace (envisage.plugins.ipython_kernel.tests.test_internal_ipkernel.TestInternalIPKernel) ... /home/travis/.edm/envs/envisage-test-3.6-pyqt/lib/python3.6/site-packages/ipykernel/kernelapp.py:465: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
`

seen in https://github.com/enthought/envisage/pull/222

**Comment by mdickinson** [comment] 2019-09-22 12:44
This is coming from upstream, so there may not be much we can do about it except perhaps do a `filterwarnings` to silence it. I'd argue that we shouldn't be doing that here, though (libraries shouldn't mess with global state that doesn't belong to them), but instead in the applications using Envisage.

OTOH, if we can find a way to filter the warning just for the test suite run, that could be good. (Test suites count as applications.)

**Comment by mdickinson** [comment] 2019-09-22 12:46
OTOOH, we're already subclassing `kernelapp` to patch it in various ways. If the fix for the deprecation warning is trivial, we could do it there. If not, it's probably not worth messing with; ideally, we want to keep our divergence from the upstream `kernelapp` to a minimum.

**Comment by mdickinson** [comment] 2019-10-09 09:46
It doesn't look as though there's anything easy we can do to fix this warning: it's an issue with `kernelapp`, and it looks as though it's still an issue on the master branch of `ipykernel`: https://github.com/ipython/ipykernel/blob/0faac5c1089f171011e2e6467c464cc0c1df7508/ipykernel/kernelapp.py#L523, so updating to a newer `ipykernel` isn't going to help.

Actually, on further inspection, this is also an internal problem in pyzmq: `zmq.eventloop.zmqstream.ZMQStream` doesn't seem to be deprecated, but it uses machinery that is: https://github.com/zeromq/pyzmq/blob/b99ff8d49a80b386ab66f233fe95f356862a0c2a/zmq/eventloop/zmqstream.py#L115

and again, that's still the case in master.

**Comment by mdickinson** [comment] 2020-02-18 09:30
I can no longer reproduce these warnings. I assume that this is due to changes in upstream packages . Closing here.

**Closed by mdickinson** 2020-02-18 09:30 UTC
